
Listen 80
============================

<VirtualHost *:80>

    ServerName ec2-84287932443289734.compute.amazonaws.com

    DocumentRoot /var/www/html

    Redirect "/" "https://ec2-84287932443289734.compute.amazonaws.com/"

</VirtualHost>


<VirtualHost *:443>

    ServerName ec2-84287932443289734.compute.amazonaws.com

    DocumentRoot /var/www/html

    SSLEngine on

    SSLCertificateFile /etc/letsencrypt/live/ec2-84287932443289734.compute.amazonaws.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/ec2-84287932443289734.compute.amazonaws.com/privkey.pem

    # Strong SSL Protocols
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1

    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "DENY"
    Header always set X-XSS-Protection "1; mode=block"

    <Directory "/var/www/html">
        AllowOverride All
        Require all granted
    </Directory>

    ProxyPreserveHost On

    ProxyPass "/api" "http://localhost:8080/api"
    ProxyPassReverse "/api" "http://localhost:8080/api"

    ErrorLog logs/secureapp-error.log
    CustomLog logs/secureapp-access.log combined

</VirtualHost>